# Generated by Django 5.0.6 on 2024-07-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_1', models.IntegerField()),
                ('goals_2', models.IntegerField()),
                ('teams', models.ManyToManyField(to='game.team')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='matches',
            field=models.ManyToManyField(to='game.match'),
        ),
    ]
